// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {stats} from '../models';

export function GetStats(arg1:string):Promise<stats.Stats>;

export function Greet(arg1:string):Promise<string>;
